MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "https://download.pytorch.org/models/resnet18-5c106cde.pth"
  RPN_ONLY: True
  FCOS_VISDRONE_ON: True
  BACKBONE:
    CONV_BODY: "R-18-FPN-234"
    FREEZE_CONV_BODY_AT: 2
  RESNETS:
    BACKBONE_OUT_CHANNELS: 128
  RETINANET:
    USE_C5: False # FCOS_SPCONV uses P5 instead of C5
  FCOS_VISDRONE:
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    # positioning centerness on the regress branch.
    # Please refer to https://github.com/tianzhi0549/FCOS/issues/89#issuecomment-516877042
    CENTERNESS_ON_REG: True
    # using center sampling and GIoU.
    # Please refer to https://github.com/yqyao/FCOS_PLUS
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
    NUM_CONVS: 4

    HEAD_NORM_TYPE: 'GN'
    FPN_STRIDES: [4, 8, 16]
    OBJECT_SIZES_OF_INTEREST: [[-1, 32], [32, 64], [64, 100000000]]
DATASETS:
  TRAIN: ("visdrone_2019_train", )
  TEST: ("visdrone_2019_val", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  ADD_EXTRA_AUG: False
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
  WARMUP_METHOD: "constant"
TEST:
  DETECTIONS_PER_IMG: 500
  IMS_PER_BATCH: 8
  FUSE_BN: True
VISUALIZE:
  ENV: 'fcos_imprv_R_18_FPN_1x_800x1333_visdrone_gn_lr0.0025'
  PERIOD: 2000